USE dcase;

DELETE FROM node;
DELETE FROM commit;
DELETE FROM dcase;
DELETE FROM user;

ALTER TABLE node   AUTO_INCREMENT = 1;
ALTER TABLE dcase  AUTO_INCREMENT = 1;
ALTER TABLE commit AUTO_INCREMENT = 1;
ALTER TABLE user   AUTO_INCREMENT = 1;
